In [ ]:
import pandas as pd
import yfinance as yf
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Final data btp.csv")

In [ ]:
df.head(14)

,Year,Firm,SigSize,Nar,CEO_Change,Narcissism_Change,Revenue,Total Assets,Total Expenses,Total Liabilities,Profit After Tax,ROE
0,2010,Bajaj Finance,5,1.6094,0,0,NaN,4828.84,873.78,4828.84,89.41,0.15
1,2011,Bajaj Finance,5,1.6094,0,0,NaN,8522.92,1222.51,8522.92,246.96,0.15
2,2012,Bajaj Finance,5,1.6094,0,0,NaN,12932.74,1846.43,12932.74,406.44,0.17
3,2013,Bajaj Finance,5,1.6094,0,0,NaN,17815.26,2593.66,17815.26,591.31,0.19
4,2014,Bajaj Finance,5,1.6094,0,0,NaN,24630.07,3417.26,24630.07,719.01,0.17
5,2015,Bajaj Finance,5,1.6094,0,0,5392.0,34054.66,4659.83,34054.66,897.87,0.19
6,2016,Bajaj Finance,5,1.6094,0,0,7299.0,49473.94,6054.86,49473.94,1278.52,0.21
7,2017,Bajaj Finance,5,1.6094,0,0,9970.0,67292.96,8152.42,67292.96,1836.55,0.22
8,2018,Bajaj Finance,5,1.6094,0,0,12746.0,83156.49,10235.06,83156.49,2484.51,0.20
9,2019,Bajaj Finance,5,1.6094,0,0,18487.0,110543.14,13523.21,110543.14,3890.34,0.22
10,2020,Bajaj Finance,5,1.6094,0,0,26374.0,141644.01,19023.49,141644.01,4881.12,0.20
11,2021,Bajaj Finance,5,1.6094,0,0,26673.0,142272.58,19608.38,142272.58,3955.51,0.13
12,2022,Bajaj Finance,5,1.6094,0,0,31641.0,171984.08,21553.09,171984.08,6350.49,0.17
13,2023,Bajaj Finance,5,1.6094,0,0,41398.0,220417.99,25419.68,220417.99,10289.74,0.23

In [ ]:
df.shape

(140, 12)

In [ ]:
df["Revenue"].isna().sum()

18

In [ ]:
df["Revenue"].iloc[0:14].mean()

19997.777777777777

In [ ]:
df["Revenue"].iloc[0:14].fillna(19997.78,inplace=True)

In [ ]:
df["Firm"].unique()

array(['Bajaj Finance', 'HDFC Bank', 'Hindustan Unilever', 'ICICI Bank',
       'Infosys Ltd', 'ITC Ltd', 'Kotak Mahindra Bank',
       'Larsen & Tubro Ltd', 'Reliance Industries', 'TCS Ltd'],
      dtype=object)

In [ ]:
df["Revenue"].iloc[14:28].mean()

92126.81818181818

In [ ]:
df["Revenue"].iloc[14:28].fillna(92126.82,inplace=True)

In [ ]:
df["Revenue"].iloc[42:56].mean()

71699.45454545454

In [ ]:
df["Revenue"].iloc[42:56].fillna(71699.45,inplace=True)

In [ ]:
df["Revenue"].iloc[84:97].mean()

7.085

In [ ]:
df["Revenue"].iloc[84:97].fillna(7.08,inplace=True)

In [ ]:
df["Revenue"].isna().sum()

0

In [ ]:
df.head(20)

,Year,Firm,SigSize,Nar,CEO_Change,Narcissism_Change,Revenue,Total Assets,Total Expenses,Total Liabilities,Profit After Tax,ROE
0,2010,Bajaj Finance,5,1.6094,0,0,19997.78,4828.84,873.78,4828.84,89.41,0.15
1,2011,Bajaj Finance,5,1.6094,0,0,19997.78,8522.92,1222.51,8522.92,246.96,0.15
2,2012,Bajaj Finance,5,1.6094,0,0,19997.78,12932.74,1846.43,12932.74,406.44,0.17
3,2013,Bajaj Finance,5,1.6094,0,0,19997.78,17815.26,2593.66,17815.26,591.31,0.19
4,2014,Bajaj Finance,5,1.6094,0,0,19997.78,24630.07,3417.26,24630.07,719.01,0.17
5,2015,Bajaj Finance,5,1.6094,0,0,5392.00,34054.66,4659.83,34054.66,897.87,0.19
6,2016,Bajaj Finance,5,1.6094,0,0,7299.00,49473.94,6054.86,49473.94,1278.52,0.21
7,2017,Bajaj Finance,5,1.6094,0,0,9970.00,67292.96,8152.42,67292.96,1836.55,0.22
8,2018,Bajaj Finance,5,1.6094,0,0,12746.00,83156.49,10235.06,83156.49,2484.51,0.20
9,2019,Bajaj Finance,5,1.6094,0,0,18487.00,110543.14,13523.21,110543.14,3890.34,0.22
10,2020,Bajaj Finance,5,1.6094,0,0,26374.00,141644.01,19023.49,141644.01,4881.12,0.20
11,2021,Bajaj Finance,5,1.6094,0,0,26673.00,142272.58,19608.38,142272.58,3955.51,0.13
12,2022,Bajaj Finance,5,1.6094,0,0,31641.00,171984.08,21553.09,171984.08,6350.49,0.17
13,2023,Bajaj Finance,5,1.6094,0,0,41398.00,220417.99,25419.68,220417.99,10289.74,0.23
14,2010,HDFC Bank,7,1.9459,0,0,92126.82,222556.88,17210.26,222556.88,2948.70,0.20
15,2011,HDFC Bank,7,1.9459,0,0,92126.82,277428.77,20560.36,277428.77,3926.40,0.19
16,2012,HDFC Bank,7,1.9459,0,0,92126.82,337971.51,28981.76,337971.51,5167.09,0.21
17,2013,HDFC Bank,7,1.9459,0,0,35861.00,400389.85,35331.92,400389.85,6726.28,0.21
18,2014,HDFC Bank,7,1.9459,0,0,42555.00,491658.09,40873.39,491658.09,8478.38,0.22
19,2015,HDFC Bank,7,1.9459,0,0,50666.00,590576.01,47254.15,590576.01,10215.92,0.20

In [ ]:
df.describe()

,Year,SigSize,Nar,CEO_Change,Narcissism_Change,Revenue,Total Assets,Total Expenses,Total Liabilities,Profit After Tax,ROE
count,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,1.400000e+02,140.000000,1.400000e+02,140.000000,140.000000
mean,2016.500000,6.785714,1.902306,0.064286,0.185714,83114.184857,3.038053e+05,74790.324786,3.038053e+05,12094.863000,0.229071
std,4.045603,1.044242,0.161252,0.246142,0.390272,99140.792779,4.360414e+05,94843.771861,4.360414e+05,10536.347242,0.145893
min,2010.000000,5.000000,1.609400,0.000000,0.000000,5.530000,4.828840e+03,873.780000,4.828840e+03,89.410000,0.040000
25%,2013.000000,6.000000,1.791800,0.000000,0.000000,29487.680000,5.079440e+04,25362.510000,5.079440e+04,4481.490000,0.140000
50%,2016.500000,7.000000,1.945900,0.000000,0.000000,51985.720000,1.006890e+05,42799.550000,1.006890e+05,8474.190000,0.190000
75%,2020.000000,8.000000,2.079400,0.000000,0.000000,89903.955000,3.872412e+05,79150.685000,3.872412e+05,16548.435000,0.260000
max,2023.000000,8.000000,2.079400,1.000000,1.000000,565347.000000,2.466081e+06,541506.000000,2.466081e+06,44205.000000,0.840000

In [ ]:
# Create interaction term
df['Interaction'] = df['CEO_Change'] * df['Narcissism_Change']

In [ ]:
df.head(10)

,Year,Firm,SigSize,Nar,CEO_Change,Narcissism_Change,Revenue,Total Assets,Total Expenses,Total Liabilities,Profit After Tax,ROE,Interaction
0,2010,Bajaj Finance,5,1.6094,0,0,19997.78,4828.84,873.78,4828.84,89.41,0.15,0
1,2011,Bajaj Finance,5,1.6094,0,0,19997.78,8522.92,1222.51,8522.92,246.96,0.15,0
2,2012,Bajaj Finance,5,1.6094,0,0,19997.78,12932.74,1846.43,12932.74,406.44,0.17,0
3,2013,Bajaj Finance,5,1.6094,0,0,19997.78,17815.26,2593.66,17815.26,591.31,0.19,0
4,2014,Bajaj Finance,5,1.6094,0,0,19997.78,24630.07,3417.26,24630.07,719.01,0.17,0
5,2015,Bajaj Finance,5,1.6094,0,0,5392.00,34054.66,4659.83,34054.66,897.87,0.19,0
6,2016,Bajaj Finance,5,1.6094,0,0,7299.00,49473.94,6054.86,49473.94,1278.52,0.21,0
7,2017,Bajaj Finance,5,1.6094,0,0,9970.00,67292.96,8152.42,67292.96,1836.55,0.22,0
8,2018,Bajaj Finance,5,1.6094,0,0,12746.00,83156.49,10235.06,83156.49,2484.51,0.20,0
9,2019,Bajaj Finance,5,1.6094,0,0,18487.00,110543.14,13523.21,110543.14,3890.34,0.22,0

In [ ]:
correlation_matrix = df.iloc[:,2:].corr()

In [ ]:
correlation_matrix

,SigSize,Nar,CEO_Change,Narcissism_Change,Revenue,Total Assets,Total Expenses,Total Liabilities,Profit After Tax,ROE,Interaction
SigSize,1.000000,0.997310,-0.057979,0.310187,0.327756,0.108932,0.352502,0.108932,0.140316,-0.266234,0.117730
Nar,0.997310,1.000000,-0.058339,0.312707,0.311925,0.118708,0.337851,0.118708,0.140268,-0.242355,0.117776
CEO_Change,-0.057979,-0.058339,1.000000,0.174390,-0.024489,0.096696,-0.025742,0.096696,0.052645,-0.030380,0.654297
Narcissism_Change,0.310187,0.312707,0.174390,1.000000,-0.190087,-0.279130,-0.193638,-0.279130,-0.096049,0.347992,0.359109
Revenue,0.327756,0.311925,-0.024489,-0.190087,1.000000,0.374673,0.988820,0.374673,0.747816,-0.210736,-0.064307
Total Assets,0.108932,0.118708,0.096696,-0.279130,0.374673,1.000000,0.377764,1.000000,0.542764,-0.354403,-0.101764
Total Expenses,0.352502,0.337851,-0.025742,-0.193638,0.988820,0.377764,1.000000,0.377764,0.727386,-0.243830,-0.065208
Total Liabilities,0.108932,0.118708,0.096696,-0.279130,0.374673,1.000000,0.377764,1.000000,0.542764,-0.354403,-0.101764
Profit After Tax,0.140316,0.140268,0.052645,-0.096049,0.747816,0.542764,0.727386,0.542764,1.000000,0.069360,-0.051564
ROE,-0.266234,-0.242355,-0.030380,0.347992,-0.210736,-0.354403,-0.243830,-0.354403,0.069360,1.000000,0.012893
Interaction,0.117730,0.117776,0.654297,0.359109,-0.064307,-0.101764,-0.065208,-0.101764,-0.051564,0.012893,1.000000

In [ ]:
control_variables = ['SigSize','Nar','Revenue','Total Assets','Total Expenses','Total Liabilities','Profit After Tax']

In [ ]:
# Define the regression formula
formula = 'ROE ~ CEO_Change + Narcissism_Change + Interaction + ' + ' + '.join(control_variables)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               140 non-null    int64
 1   Firm               140 non-null    object
 2   SigSize            140 non-null    int64
 3   Nar                140 non-null    float64
 4   CEO_Change         140 non-null    int64
 5   Narcissism_Change  140 non-null    int64
 6   Revenue            140 non-null    float64
 7   Total Assets       140 non-null    float64
 8   Total Expenses     140 non-null    float64
 9   Total Liabilities  140 non-null    float64
 10  Profit After Tax   140 non-null    float64
 11  ROE                140 non-null    float64
 12  Interaction        140 non-null    int64
dtypes: float64(7), int64(5), object(1)
memory usage: 14.3+ KB

In [ ]:
X = df[['CEO_Change','Year','SigSize','Nar','Narcissism_Change','Revenue','Total Assets','Total Expenses','Total Liabilities','Profit After Tax','Interaction']]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CEO_Change         140 non-null    int64
 1   Year               140 non-null    int64
 2   SigSize            140 non-null    int64
 3   Nar                140 non-null    float64
 4   Narcissism_Change  140 non-null    int64
 5   Revenue            140 non-null    float64
 6   Total Assets       140 non-null    float64
 7   Total Expenses     140 non-null    float64
 8   Total Liabilities  140 non-null    float64
 9   Profit After Tax   140 non-null    float64
 10  Interaction        140 non-null    int64
dtypes: float64(6), int64(5)
memory usage: 12.2 KB

In [ ]:
y = df[['ROE']]

In [ ]:
y.head()

    ROE
0  0.15
1  0.15
2  0.17
3  0.19
4  0.17

In [ ]:
# Add intercept
X = sm.add_constant(X)

In [ ]:
# Step 3: Fit regression model
model = sm.OLS(y, X).fit()

In [ ]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ROE   R-squared:                       0.594
Model:                            OLS   Adj. R-squared:                  0.562
Method:                 Least Squares   F-statistic:                     18.87
Date:                Tue, 30 Apr 2024   Prob (F-statistic):           6.20e-21
Time:                        11:40:24   Log-Likelihood:                 134.42
No. Observations:                 140   AIC:                            -246.8
Df Residuals:                     129   BIC:                            -214.5
Df Model:                          10
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 2.3687      6.072      0.390      0.697      -9.645      14.382
CEO_Change           -0.0131      0.047     -0.281      0.779      -0.105       0.079
Year                 -0.0026      0.003     -0.900      0.370      -0.008       0.003
SigSize              -0.6501      0.119     -5.483      0.000      -0.885      -0.415
Nar                   3.9484      0.767      5.145      0.000       2.430       5.467
Narcissism_Change     0.1278      0.028      4.575      0.000       0.073       0.183
Revenue            7.089e-07   6.61e-07      1.073      0.285   -5.99e-07    2.02e-06
Total Assets      -9.587e-08   4.31e-08     -2.222      0.028   -1.81e-07   -1.05e-08
Total Expenses    -1.149e-06   6.63e-07     -1.733      0.086   -2.46e-06    1.63e-07
Total Liabilities -6.751e-08   4.85e-08     -1.392      0.166   -1.63e-07    2.84e-08
Profit After Tax   8.638e-06    1.6e-06      5.415      0.000    5.48e-06    1.18e-05
Interaction          -0.0872      0.071     -1.233      0.220      -0.227       0.053
==============================================================================
Omnibus:                       82.492   Durbin-Watson:                   0.587
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              450.692
Skew:                           2.092   Prob(JB):                     1.36e-98
Kurtosis:                      10.730   Cond. No.                     1.21e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.5e-19. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.